import { db } from "./src/db";
import { products, category } from "./src/db/schema";

// Categories data
export const categoriesData = [
  {
    id: "61b8d170-a9f5-4677-9fbc-c40e17ef9bef",
    name: "Affordable",
    description: "For budget friendly moments",
    imageUrl: "/Affordable - banner.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6eb3e51a-465b-41ac-a4d8-ee21a5db589c",
    name: "Prestiá",
    description: "Most Expensive lime time momments for some one need",
    imageUrl: "/Premium - banner.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "827fe297-840c-4e26-a8de-71a70c9d9805",
    name: "Royal",
    description: "Most premimum moments don't think about the price",
    imageUrl: "/Luxe - banner.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Products data with category assignments and pricing tiers
export const productsData = [
  {
    name: "Birdsong Serenity",
    description:
      "Make your gift stand out with this exquisite designer envelope crafted for weddings and special occasions. Featuring a rich peacock teal backdrop, the envelope is adorned with a luxurious gold foil tree at the center, symbolizing growth and prosperity. Beautifully illustrated birds perched on branches add a touch of charm and warmth, making it a perfect blend of tradition and elegance.\n\nThe flap is detailed with diagonal gold stripes and a sleek cut, enhancing its modern appeal. The names are delicately printed in gold, giving it a personalized, premium feel.",
    price: 65,
    categoryId: "6eb3e51a-465b-41ac-a4d8-ee21a5db589c", // Prestiá
    inventory: 87,
    imageUrl: "/Ready for post/Birdsong Serenity/1.jpg",
    productImages: [
      "/Ready for post/Birdsong Serenity/1.jpg",
      "/Ready for post/Birdsong Serenity/2.jpg",
      "/Ready for post/Birdsong Serenity/3.jpg",
      "/Ready for post/Birdsong Serenity/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "High-grade paper with foil detailing",
    customization: "Name/text personalization available on request",
    features: [
      "Premium quality cardstock with matte finish",
      "Gold foil embossed tree and accents",
      "Vibrant and artistic bird illustrations",
      "Modern diagonal stripe flap design",
      "Ideal for wedding gifts, invitations, or cash gifting",
    ],
    costPrice: 20,
    setOf10: 65,
    setof20: 63,
    setof50: 62,
    setof100: 60,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Golden Vine",
    description:
      'Add a timeless touch to your heartfelt wishes with this beautifully designed wedding envelope. Styled in a warm, elegant cream base with a sophisticated gold half-moon flap, the envelope exudes understated luxury. The subtle diagonal embossing on the flap and delicate floral corner motifs create a graceful harmony of tradition and style.\n\nThe text "Best Wishes" and {Your Name} is printed in classic serif typography, making it perfect for gifting during weddings, engagements, anniversaries, or festive celebrations.',
    price: 58,
    categoryId: "61b8d170-a9f5-4677-9fbc-c40e17ef9bef", // Affordable
    inventory: 99,
    imageUrl: "/Ready for post/Golden Vine/1.jpg",
    productImages: [
      "/Ready for post/Golden Vine/1.jpg",
      "/Ready for post/Golden Vine/2.jpg",
      "/Ready for post/Golden Vine/3.jpg",
      "/Ready for post/Golden Vine/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "High-quality paper with foil finish",
    customization: "Personal names/text can be added",
    features: [
      "Premium textured paper with gold sheen",
      "Elegant half-moon gold foil flap with subtle embossed stripes",
      "Delicate floral artwork in rich festive tones",
      "Personalized message option available",
      "Ideal for weddings, anniversaries, festive gifts, or cash gifting",
    ],
    costPrice: 20,
    setOf10: 45,
    setof20: 43,
    setof50: 42,
    setof100: 40,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Rose Garden",
    description:
      'Bring timeless charm to your celebrations with this romantic rose-themed wedding envelope. The rich maroon half-moon flap, embossed with diagonal gold lines and adorned with the message "Best Wishes –Your Name," creates a stunning contrast against the soft lavender background.\n\nDelicate vintage rose illustrations bloom on both sides of the envelope, enhanced with gold foil accents, making it the perfect pick for weddings, bridal showers, or elegant gifting moments.',
    price: 12,
    categoryId: "827fe297-840c-4e26-a8de-71a70c9d9805", // Royal
    inventory: -20,
    imageUrl: "/Ready for post/Rose Garden/1.jpg",
    productImages: [
      "/Ready for post/Rose Garden/1.jpg",
      "/Ready for post/Rose Garden/2.jpg",
      "/Ready for post/Rose Garden/3.jpg",
      "/Ready for post/Rose Garden/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium quality paper with foil finish",
    customization: "Names or custom message can be printed on request",
    features: [
      "Luxurious maroon and blush color palette",
      "Gold foil detailing on flap and body",
      "Soft floral rose design on high-quality paper",
      "Personalized message printing available",
      "Ideal for weddings, anniversaries, bridal showers, or festive gifting",
    ],
    costPrice: 20,
    setOf10: 90,
    setof20: 90,
    setof50: 90,
    setof100: 85,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Eternal Tree",
    description:
      'Add a regal touch to your celebrations with this luxurious midnight blue wedding envelope. Crafted with precision and elegance, this envelope features a deep blue backdrop accented by a radiant gold foil tree symbolizing prosperity and unity. Two golden birds perched on delicate branches frame the design, evoking a sense of harmony and grace.\n\nThe top flap is styled with sleek diagonal gold lines over a rich navy tone, while the center displays the custom message "Best Wishes – Your Name" in refined typography. This envelope is perfect for gifting cash, invitations, or blessings during weddings and formal occasions.',
    price: 68,
    categoryId: "827fe297-840c-4e26-a8de-71a70c9d9805", // Royal
    inventory: 84,
    imageUrl: "/Ready for post/Eternal Tree/1.jpg",
    productImages: [
      "/Ready for post/Eternal Tree/1.jpg",
      "/Ready for post/Eternal Tree/2.jpg",
      "/Ready for post/Eternal Tree/3.jpg",
      "/Ready for post/Eternal Tree/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium-grade textured paper with foil finish",
    customization: "Personalization of names or message upon request",
    features: [
      "Striking midnight blue base with shimmering gold accents",
      "Gold foil embossed tree and bird motifs",
      "Diagonal line detailing on elegant envelope flap",
      "Custom name/message personalization available",
      "Ideal for weddings, anniversaries, housewarmings, or formal gifting",
    ],
    costPrice: 20,
    setOf10: 95,
    setof20: 95,
    setof50: 95,
    setof100: 90,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Olive & Rose",
    description:
      'Delight your loved ones with this charming pastel-themed wedding envelope, featuring a soft blend of tradition and modern elegance. The envelope\'s deep sage green flap, detailed with gold diagonal stripes and delicate script reading "Best Wishes – Your Name", adds a graceful sophistication.\n\nThe body of the envelope is framed with soft blush floral corners and a pale watercolor wash background—perfect for weddings, bridal showers, or spring-themed gifting. Its subtle luxury and artistic floral design make it a memorable choice for heartfelt moments.',
    price: 60,
    categoryId: "61b8d170-a9f5-4677-9fbc-c40e17ef9bef", // Affordable
    inventory: 99,
    imageUrl: "/Ready for post/Olive & Rose/1.jpg",
    productImages: [
      "/Ready for post/Olive & Rose/1.jpg",
      "/Ready for post/Olive & Rose/2.jpg",
      "/Ready for post/Olive & Rose/3.jpg",
      "/Ready for post/Olive & Rose/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "High-quality matte paper with foil embellishments",
    customization: "Personalization available with names or custom message",
    features: [
      "Elegant sage green and blush pink color palette",
      "Gold foil detailing with customizable name/message",
      "Soft watercolor floral design on premium textured paper",
      "Ideal for weddings, baby showers, anniversaries, or festive cash gifting",
    ],
    costPrice: 20,
    setOf10: 45,
    setof20: 43,
    setof50: 42,
    setof100: 40,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Rosé & Mint",
    description:
      'Charmingly romantic and refreshingly modern, our Striped Pastel Bloom Envelope is a delightful choice for weddings, engagements, or special gifting occasions. Featuring a soothing aqua and white striped pattern adorned with watercolor roses, peonies, and soft botanical accents, this envelope brings together grace and cheer in every detail.\n\nThe unique flap design with a centered rose motif and gold foil edging adds a luxe touch, while the personalized message – "Best Wishes – Your Name" – adds warmth and thoughtfulness.',
    price: 64,
    categoryId: "827fe297-840c-4e26-a8de-71a70c9d9805", // Royal
    inventory: -61,
    imageUrl: "/Ready for post/Rosé & Mint/1.jpg",
    productImages: [
      "/Ready for post/Rosé & Mint/1.jpg",
      "/Ready for post/Rosé & Mint/2.jpg",
      "/Ready for post/Rosé & Mint/3.jpg",
      "/Ready for post/Rosé & Mint/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "High-grade matte finish paper with foil accents",
    customization: "names, message",
    features: [
      "Aqua-striped background with elegant floral overlays",
      "Watercolor rose centerpiece on the flap",
      "Gold foil detailing for a premium finish",
      "Printed names/messages for a personalized touch",
      "Ideal for weddings, festive gifting, baby showers, and anniversaries",
    ],
    costPrice: 20,
    setOf10: 90,
    setof20: 90,
    setof50: 90,
    setof100: 85,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Olive Bloom",
    description:
      'Subtle sophistication meets earthy charm in our Olive Bloom Elegance Envelope. Designed with muted olive green tones and a stylish striped pattern, this piece is beautifully accented by soft florals in dusky rose and warm yellow hues. A perfect blend of contemporary structure and organic warmth.\n\nThe structured flap with vertical gold foil stripes adds a premium feel, while the central message – "Best Wishes – Your Name" – brings a personal, heartfelt touch to any occasion.',
    price: 59,
    categoryId: "6eb3e51a-465b-41ac-a4d8-ee21a5db589c", // Prestiá
    inventory: 98,
    imageUrl: "/Ready for post/Olive Bloom/1.jpg",
    productImages: [
      "/Ready for post/Olive Bloom/1.jpg",
      "/Ready for post/Olive Bloom/2.jpg",
      "/Ready for post/Olive Bloom/3.jpg",
      "/Ready for post/Olive Bloom/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "High-quality textured cardstock with foil print",
    customization: "custom names/messages",
    features: [
      "Earthy olive green palette with horizontal stripes",
      "Elegant floral corners in watercolor style",
      "Gold foil detailing on flap for a luxurious finish",
      "Personalized name/message section",
      "Ideal for weddings, eco-themed events, gifting & more",
    ],
    costPrice: 20,
    setOf10: 65,
    setof20: 63,
    setof50: 62,
    setof100: 60,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mystic Mountain",
    description:
      'Capture the calm of nature with our Midnight Serenity Envelope, a breathtaking piece featuring a layered silhouette of serene blue mountains, peaceful pine trees, and a glassy lake under a moonlit sky. Accentuated with a graceful flight of birds, this envelope speaks of elegance, depth, and timeless tranquility.\n\nThe flap is adorned with a modern geometric gold-foil lattice, adding a sophisticated contrast to the scenic bottom half. A heartfelt "Best Wishes – Your Name" message adds a personalized, warm touch for every occasion.',
    price: 72,
    categoryId: "827fe297-840c-4e26-a8de-71a70c9d9805", // Royal
    inventory: -569,
    imageUrl: "/Ready for post/Mystic Mountain/1.jpg",
    productImages: [
      "/Ready for post/Mystic Mountain/1.jpg",
      "/Ready for post/Mystic Mountain/2.jpg",
      "/Ready for post/Mystic Mountain/3.jpg",
      "/Ready for post/Mystic Mountain/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Fine textured cardstock with foil finish",
    customization: "Available on request",
    features: [
      "Tranquil mountain and forest lake design in gradient blues",
      "Elegant geometric gold foil flap",
      "Premium matte finish with crisp detailing",
      "Personalized message included",
      "Perfect for weddings, special celebrations, and gifting",
    ],
    costPrice: 20,
    setOf10: 100,
    setof20: 100,
    setof50: 100,
    setof100: 95,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Castle in Bloom",
    description:
      "Step into a world of charm with our Blush Fairytale Envelope, a delicate blend of floral elegance and whimsical fantasy. Featuring soft pink roses, fluttering butterflies, and an enchanting castle centerpiece, this design brings a magical touch to your heartfelt wishes.\n\nWith its pastel palette and refined layout, the envelope is ideal for weddings, birthdays, baby showers, or any celebration that calls for a fairytale touch. The flap is finished with a gold-trimmed edge and personalized wishes from Your Name, giving it a luxurious and heartfelt appeal.",
    price: 66,
    categoryId: "827fe297-840c-4e26-a8de-71a70c9d9805", // Royal
    inventory: -759,
    imageUrl: "/Ready for post/Castle in Bloom/1.jpg",
    productImages: [
      "/Ready for post/Castle in Bloom/1.jpg",
      "/Ready for post/Castle in Bloom/2.jpg",
      "/Ready for post/Castle in Bloom/3.jpg",
      "/Ready for post/Castle in Bloom/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "High-quality matte cardstock",
    customization: "Names and messages can be personalized",
    features: [
      "Dreamy castle illustration surrounded by blush florals and butterflies",
      "Soft pastel tones with a clean, elegant finish",
      "Premium textured paper with gold border detailing",
      "Personalized message on flap",
      "Perfect for fairytale-themed occasions and gifting",
    ],
    costPrice: 20,
    setOf10: 90,
    setof20: 90,
    setof50: 90,
    setof100: 85,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Enchanted Aviary",
    description:
      "Elevate your gifting with the Royal Violet Bloom Envelope, where vibrant elegance meets artistic charm. This captivating design showcases a rich violet backdrop adorned with flourishing pink blossoms and a whimsical birdhouse, evoking the serenity of a blooming garden.\n\nAccentuated with gold foiling and a unique half-moon flap, this envelope adds a sophisticated touch to your heartfelt messages. The personal wish from Your Name printed in regal gold makes it perfect for weddings, anniversaries, or festive occasions.",
    price: 70,
    categoryId: "61b8d170-a9f5-4677-9fbc-c40e17ef9bef", // Affordable
    inventory: 100,
    imageUrl: "/Ready for post/Enchanted Aviary/1.jpg",
    productImages: [
      "/Ready for post/Enchanted Aviary/1.jpg",
      "/Ready for post/Enchanted Aviary/2.jpg",
      "/Ready for post/Enchanted Aviary/3.jpg",
      "/Ready for post/Enchanted Aviary/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Elegant deep purple base with intricate floral and birdhouse illustration",
      "Unique curved flap design with gold foil detailing",
      "Premium-quality matte finish paper for a luxurious feel",
      'Personal touch with "Best Wishes" from Seema Shah & Shrenik Shah',
      "Ideal for celebrations, special occasions, or premium gifting",
    ],
    costPrice: 20,
    setOf10: 45,
    setof20: 43,
    setof50: 42,
    setof100: 40,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ocean Opulence",
    description:
      "Celebrate special moments with elegance and style using our Regal Beach-Themed Wedding Envelope. Adorned with serene coastal illustrations, lush palm trees, and a majestic peacock by a traditional dome, this envelope is perfect for gifting on weddings, anniversaries, or festive occasions.",
    price: 74,
    categoryId: "61b8d170-a9f5-4677-9fbc-c40e17ef9bef", // Affordable
    inventory: 100,
    imageUrl: "/Ready for post/Ocean Opulence/1.jpg",
    productImages: [
      "/Ready for post/Ocean Opulence/1.jpg",
      "/Ready for post/Ocean Opulence/2.jpg",
      "/Ready for post/Ocean Opulence/3.jpg",
      "/Ready for post/Ocean Opulence/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Premium Quality: Crafted from high-grade textured paper with a luxurious matte finish",
      "Elegant Gold Border: Adds a sophisticated touch to the classic white flap",
      'Personalized Message: Pre-printed with "Best Wishes" and sender names – customizable',
      "Scenic Artwork: A calming seaside backdrop with graceful birds and vibrant tropical elements",
      "Traditional Meets Modern: The peacock and dome motif blend cultural charm with contemporary design",
    ],
    costPrice: 20,
    setOf10: 45,
    setof20: 43,
    setof50: 42,
    setof100: 40,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Lavender Lace",
    description:
      "Present your heartfelt wishes in timeless style with our Royal Lavender Floral Envelope, a sophisticated blend of elegance and floral artistry. The envelope features a unique half-moon flap in deep royal purple, accented with bold gold diagonal stripes and delicate foil typography.",
    price: 63,
    categoryId: "6eb3e51a-465b-41ac-a4d8-ee21a5db589c", // Prestiá
    inventory: -23,
    imageUrl: "/Ready for post/Lavender Lace/3.jpg",
    productImages: [
      "/Ready for post/Lavender Lace/1.jpg",
      "/Ready for post/Lavender Lace/2.jpg",
      "/Ready for post/Lavender Lace/3.jpg",
      "/Ready for post/Lavender Lace/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Premium Finish: High-quality card stock with a matte texture and gold foil detailing for a luxurious look",
      "Elegant Color Scheme: A refined blend of lavender, violet, and cream with vintage floral illustrations in monochrome purple tones",
      "Personalized Touch: Printed with sender names – perfect for wedding gifts, receptions, and special occasions. Bulk customization available",
      "Classical Meets Contemporary: A fusion of timeless floral art and modern layout with rich visual appeal",
      "Gold-Lined Edges: Adds a premium feel, making it ideal for money gifting, invitations, or thank-you notes",
    ],
    costPrice: 20,
    setOf10: 65,
    setof20: 63,
    setof50: 62,
    setof100: 60,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Rainforest Royalty",
    description:
      "Infuse your celebrations with the beauty of nature using our Monsoon Majesty Peacock Envelope, a striking piece inspired by lush greenery and the charm of the Indian monsoon. Featuring a vibrant peacock amidst tropical foliage and falling rain, this envelope captures elegance and festivity in one refined package.",
    price: 76,
    categoryId: "61b8d170-a9f5-4677-9fbc-c40e17ef9bef", // Affordable
    inventory: 98,
    imageUrl: "/Ready for post/Rainforest Royalty/1.jpg",
    productImages: [
      "/Ready for post/Rainforest Royalty/1.jpg",
      "/Ready for post/Rainforest Royalty/2.jpg",
      "/Ready for post/Rainforest Royalty/3.jpg",
      "/Ready for post/Rainforest Royalty/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Nature-Inspired Artwork: A stunning peacock surrounded by palm leaves and raindrops brings freshness and vibrancy to your gifting experience",
      "Premium Craftsmanship: Made from high-quality card stock with a smooth matte finish and gold foil accents for a luxe touch",
      "Sophisticated Flap Design: The green striped flap with metallic gold detailing adds a contemporary edge to a traditional concept",
      "Custom Name Print: Includes pre-printed sender names – ideal for personalized wedding gifting. Custom orders available for bulk quantities",
      "Ideal For: Festive Gifting: Suitable for weddings, engagements, festive gifting, or as part of traditional ceremonies",
    ],
    costPrice: 20,
    setOf10: 45,
    setof20: 43,
    setof50: 42,
    setof100: 40,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Whispers of Spring",
    description:
      "Delight in understated charm with our Blush Garden Bird Envelope, where minimalism meets artistic grace. Featuring soft pastel florals and a delicate bird motif, this envelope exudes a warm, nature-inspired serenity—ideal for weddings, engagements, or refined festive gifting.",
    price: 56,
    categoryId: "61b8d170-a9f5-4677-9fbc-c40e17ef9bef", // Affordable
    inventory: 12,
    imageUrl: "/Ready for post/Whispers of Spring/1.jpg",
    productImages: [
      "/Ready for post/Whispers of Spring/1.jpg",
      "/Ready for post/Whispers of Spring/2.jpg",
      "/Ready for post/Whispers of Spring/3.jpg",
      "/Ready for post/Whispers of Spring/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Elegant Florals & Bird Artwork: Watercolor-style blooms and a charming bird illustration create a gentle, romantic vibe",
      "Premium Paper Quality: Crafted from smooth, high-grade cardstock with a matte finish and gold foil edges for a luxurious feel",
      "Sophisticated Color Palette: Hues of ivory, blush, and beige with muted floral accents for a timeless aesthetic",
      'Custom Name Print: Embellished with "Best Wishes – Your Name" in gold foil; customizable for bulk or special orders',
      "Versatile Use: Perfect for weddings, anniversaries, festive blessings, or heartfelt notes",
    ],
    costPrice: 20,
    setOf10: 45,
    setof20: 43,
    setof50: 42,
    setof100: 40,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ornate",
    description:
      "Elevate your gift-giving with the timeless elegance of our Midnight Bloom Floral Envelope, a stunning combination of deep navy tones and vibrant floral accents. Adorned with rich golden foil and cheerful blossoms, this envelope exudes sophistication and warmth for any special occasion.",
    price: 69,
    categoryId: "6eb3e51a-465b-41ac-a4d8-ee21a5db589c", // Prestiá
    inventory: 100,
    imageUrl: "/Ready for post/Ornate/3.jpg",
    productImages: [
      "/Ready for post/Ornate/1.jpg",
      "/Ready for post/Ornate/2.jpg",
      "/Ready for post/Ornate/3.jpg",
      "/Ready for post/Ornate/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Elegant Floral Detailing: Bright orange, yellow, and blue flowers add a vivid pop against a deep navy background",
      "Luxurious Gold Accents: Diagonal gold stripes on the flap and name personalization in radiant foil enhance its premium appeal",
      "Premium Paper Quality: Made from thick, matte-finish cardstock with gold-lined edges for a regal touch",
      'Personalized Greeting: Features "Best Wishes Your Name" in elegant calligraphy—fully customizable for bulk or bespoke gifting',
      "Perfect For: Weddings, anniversaries, festive gifting, or heartfelt blessings",
    ],
    costPrice: 20,
    setOf10: 65,
    setof20: 63,
    setof50: 62,
    setof100: 60,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Floral Blush",
    description:
      "Delicate, dreamy, and beautifully romantic, the Blush Bloom Envelope is a celebration of charm and elegance. Wrapped in soft pink hues with blossoming rose floral corners and a chic half-moon flap, this envelope is perfect for expressing warm wishes with grace.",
    price: 57,
    categoryId: "6eb3e51a-465b-41ac-a4d8-ee21a5db589c", // Prestiá
    inventory: 99,
    imageUrl: "/Ready for post/Floral Blush/1.jpg",
    productImages: [
      "/Ready for post/Floral Blush/1.jpg",
      "/Ready for post/Floral Blush/2.jpg",
      "/Ready for post/Floral Blush/3.jpg",
      "/Ready for post/Floral Blush/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Soft Blush Palette: A subtle pastel pink base complemented by watercolor roses and foliage in mauve, cream, and navy tones",
      "Gold Foil Finishing: Stylish gold-edged design and foil-printed names for a touch of glamour",
      "Stylized Flap: Unique half-moon flap with diagonal gold lines adds a modern, feminine flair",
      'Personalized Message: Features "Best Wishes Your Name" in elegant script – custom printing available on request',
      "Versatile Use: Ideal for weddings, bridal showers, anniversaries, or festive gifting",
    ],
    costPrice: 20,
    setOf10: 65,
    setof20: 63,
    setof50: 62,
    setof100: 60,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Maroon Bloom",
    description:
      "Sophistication meets floral charm in the Vintage Plum Floral Envelope, a deep-toned beauty designed for moments that matter. With rich hues, elegant floral clusters, and metallic accents, this envelope adds a luxurious finishing touch to your thoughtful gifts.",
    price: 67,
    categoryId: "6eb3e51a-465b-41ac-a4d8-ee21a5db589c", // Prestiá
    inventory: -110,
    imageUrl: "/Ready for post/Maroon Bloom/3.jpg",
    productImages: [
      "/Ready for post/Maroon Bloom/1.jpg",
      "/Ready for post/Maroon Bloom/2.jpg",
      "/Ready for post/Maroon Bloom/3.jpg",
      "/Ready for post/Maroon Bloom/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Deep Plum Base: A regal, dark plum background enhanced with floral prints in soft peach, yellow, and blue for a vintage yet vibrant look",
      "Modern Flap Design: Diagonal pinstripes on the flap outlined in gold foil create a striking contrast and contemporary edge",
      'Gold Foil Personalization: Embellished with "Best Wishes Your Name" in radiant gold script — customization available for bulk gifting',
      "Premium Quality: Crafted from durable matte-finish card stock with detailed gold lining for a luxury feel",
      "Occasion-Ready: Ideal for weddings, engagements, festive gifting, or special celebrations",
    ],
    costPrice: 20,
    setOf10: 65,
    setof20: 63,
    setof50: 62,
    setof100: 60,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Elephant Trail",
    description:
      "Take your gifting experience on a journey through nature with the Royal Wilderness Envelope. This vibrant design features majestic elephants amid pine forests and mountain peaks, offering a scenic blend of Indian heritage and tranquil landscapes.",
    price: 78,
    categoryId: "827fe297-840c-4e26-a8de-71a70c9d9805", // Royal
    inventory: -120,
    imageUrl: "/Ready for post/Elephant Trail/1.jpg",
    productImages: [
      "/Ready for post/Elephant Trail/1.jpg",
      "/Ready for post/Elephant Trail/2.jpg",
      "/Ready for post/Elephant Trail/3.jpg",
      "/Ready for post/Elephant Trail/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Scenic Forest Artwork: A lively depiction of decorated elephants walking by serene lakes and lush evergreens, with majestic mountains in the backdrop",
      "Elegant Flap Design: Deep charcoal-black flap with a sleek gold border, adding a luxurious contrast to the vibrant illustration below",
      'Gold Foil Personalization: Embossed with "Best Wishes Your Name" in elegant gold lettering—customizable for special occasions and bulk orders',
      "High-Quality Craftsmanship: Made from thick, durable cardstock with a smooth matte finish for a rich hand-feel",
      "Ideal For: Weddings, baby showers, festive gifting, or as a premium money envelope with a cultural twist",
    ],
    costPrice: 20,
    setOf10: 90,
    setof20: 90,
    setof50: 90,
    setof100: 85,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Golden Stripe Rose",
    description:
      "Add a touch of sophistication to your special occasions with our Elegant Floral Envelope Gift Box. Designed with chic navy and black vertical stripes on a cream base, this unique gift box opens like a luxurious envelope to reveal a charming pink rose accent. The gold detailing along the borders adds a hint of luxury, making it perfect for weddings, anniversaries, birthdays, or premium corporate gifting.",
    price: 71,
    categoryId: "827fe297-840c-4e26-a8de-71a70c9d9805", // Royal
    inventory: 80,
    imageUrl: "/Ready for post/Golden Stripe Rose/3.jpg",
    productImages: [
      "/Ready for post/Golden Stripe Rose/1.jpg",
      "/Ready for post/Golden Stripe Rose/2.jpg",
      "/Ready for post/Golden Stripe Rose/3.jpg",
      "/Ready for post/Golden Stripe Rose/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Premium cardstock with glossy finish",
      "Unique envelope-style flap",
      "Elegant pink rose embellishment",
      "Gold foil accents for a refined look",
      "Ideal for gifting jewelry, notes, or small keepsakes",
    ],
    costPrice: 20,
    setOf10: 100,
    setof20: 100,
    setof50: 100,
    setof100: 95,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Gold-Lined Bloom",
    description:
      "Add a touch of sophistication to your special occasions with our Elegant Floral Envelope Gift Box. Designed with pink and black vertical stripes on a cream base, this unique gift box opens like a luxurious envelope to reveal a charming pink rose accent. The gold detailing along the borders adds a hint of luxury, making it perfect for weddings, anniversaries, birthdays, or premium corporate gifting.",
    price: 73,
    categoryId: "827fe297-840c-4e26-a8de-71a70c9d9805", // Royal
    inventory: -120,
    imageUrl: "/Ready for post/Gold-Lined Bloom/3.jpg",
    productImages: [
      "/Ready for post/Gold-Lined Bloom/1.jpg",
      "/Ready for post/Gold-Lined Bloom/2.jpg",
      "/Ready for post/Gold-Lined Bloom/3.jpg",
      "/Ready for post/Gold-Lined Bloom/4.jpg",
    ],
    dimensions: '7.2" x 3.2"',
    material: "Premium textured cardstock",
    customization: "Custom names/messages available on request",
    features: [
      "Premium cardstock with glossy finish",
      "Unique envelope-style flap",
      "Elegant pink rose embellishment",
      "Gold foil accents for a refined look",
      "Ideal for gifting jewelry, notes, or small keepsakes",
    ],
    costPrice: 20,
    setOf10: 95,
    setof20: 95,
    setof50: 95,
    setof100: 90,
    discount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

async function seed() {
  try {
    console.log("🌱 Starting database seeding...");

    // First, seed categories
    // console.log("📂 Seeding categories...");
    // await db.insert(category).values(categoriesData);
    // console.log("✅ Categories seeded successfully.");

    // Then, seed products
    console.log("📦 Seeding products...");
    await db.insert(products).values(productsData);
    console.log("✅ Products seeded successfully.");

    console.log("🎉 Database seeding completed successfully!");
  } catch (error) {
    console.error("❌ Failed to seed database:", error);
    process.exit(1);
  }
}

seed();
